# Generated by Django 4.1.3 on 2022-11-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='teste',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
